config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'out'
      get 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'follower' => 'relationships#follower', as: 'follower'
  end
  # get 'users/:id/out' => 'users#out', as: 'out'
  # get 'users/:id/hide' => 'users#hide', as: 'hide'
  get 'users/:id/favorites' => 'users#favorite', as: 'users_favorites'
  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get 'search' => 'questions#search'
  resource :inquiries, only: [:new, :create]
  get 'thanks' => 'inquiries#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :title, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  validates :name, presence: true
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_questions, through: :favorites, source: :question
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def active_for_authentication?
    super && (self.is_active === true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_question, only: [:create, :destroy]

  def create
    # 投稿に紐づいたコメントを作成
    @comment = @question.comments.build(comment_params)
    @comment.score = Language.get_data(comment_params[:body])
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    else
      render :error
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], question_id: params[:question_id])
    comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_question, only: [:create, :destroy]

  def create
    favorite = current_user.favorites.build(question_id: @question.id)
    favorite.save
    render :index
  end

  def destroy
    favorite = current_user.favorites.find_by(question_id: @question.id)
    favorite.destroy
    render :index
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @rank = Question.joins(:favorites).group(:question_id).order(Arel.sql('count(question_id) desc')).limit(3)
  end

  def about
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :thanks]

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      InquiryMailer.received_email(@inquiry).deliver
      redirect_to thanks_path
    else
      render :new
    end
  end

  def thanks
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_categories, only: [:index, :show, :search]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def search
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = "なんで記事を投稿しました"
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def index
    @questions = Question.page(params[:page]).reverse_order
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @questions = @category.questions.page(params[:page]).reverse_order
    end
  end

  def show
    @comment = Comment.new
    @comments = @question.comments
  end

  def edit
    if @question.user == current_user || current_user.admin?
      render :edit
    else
      redirect_to questions_path
    end
  end

  def update
    if @question.update(question_params)
      flash[:notice] = "なんで記事を編集しました"
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:notice] = "なんで記事を削除しました"
    redirect_to user_path(current_user.id)
  end

  private

  def question_params
    params.require(:question).permit(:title, :category_id, :image, :observation, :impression, :realization, :uncertainty)
  end

  def set_categories
    @categories = Category.all
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :favorite, :edit, :update, :out, :hide]

  def show
    @questions = @user.questions.page(params[:page]).reverse_order
  end

  def index
    @categories = Category.all
    @users = User.page(params[:page]).reverse_order
  end

  def favorite
    @favorite_questions = @user.favorite_questions.page(params[:page]).reverse_order
  end

  def edit
    if @user == current_user || current_user.admin?
      render :edit
    else
      redirect_to users_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def out
    if @user == current_user
      render :out
    else
      redirect_to users_path
    end
  end

  def hide
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image, :is_active)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments_form.html.erb
<% if user_signed_in? %>
  <span class="error-message"></span>
  <%= form_with model:[question, comment] do |f| %>
    <%= f.text_area :body, placeholder: "コメントをここに", class: "question-body-field" %>
    <%= f.submit %>
  <% end %>
<% else %>
　<p>ログインしてコメントをする</p>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/comments/_index.html.erb
<div class="comments-cnt">
  <%= @question.comments.count %>コメント
</div>
<div class="commments-area">
  <% comments.each do |comment| %>
    <div class="comment-item">
      <div class="comment-item-head">
        <%= attachment_image_tag comment.user, :image, size: '40x40', fallback: "no_image.png", class: "user-list-img" %>
        <%= link_to comment.user.name, user_path(comment.user), class: "comment-username" %>
        <%= comment.created_at.strftime('%Y/%m/%d') %></p>
      </div>
      <p><%= simple_format(h(comment.body)) %></p>
      <div class="sentiment-score">
        <% if user_signed_in? && current_user.admin? && comment.score.to_f < 0.5 %>
          スコア : <%= comment.score %>
          <p class="comment-delete-content">
            <%= link_to "削除", question_comment_path(comment.question, comment), method: :delete, remote: true,class: "comment-delete" %>
          </p>
        <% end %>
      </div>
      <% if comment.user == current_user %>
        <p class="comment-delete-content">
          <%= link_to "削除", question_comment_path(comment.question, comment), method: :delete, remote: true,class: "comment-delete" %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/error.js.erb
$(".error-message").html("<%= j(render 'layouts/error', obj: @comment) %>");

app/views/comments/index.js.erb
$(".comment-content").html("<%= j(render 'index', comments: @question.comments ) %>");
$("#comment_body").val("");
$(".error-message").html("");

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <P class="favorite-count">♥<%= question.favorites.count %></P>
  <% if question.favorited_by?(current_user) %>
    <p>
      <%= link_to question_favorites_path(question), remote: true, method: :delete, class: "unfavorite-btn" do %>
        ♥お気に入り
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to question_favorites_path(question), remote: true, method: :post, class: "favorite-btn" do %>
        ♡お気に入りに入れる
      <% end %>
    </p>
  <% end %>
<% else %>
  <p class="favorite-count">♥<%= question.favorites.count %></p>
<% end %>

app/views/favorites/index.js.erb
$(".favorite-btn-<%= @question.id %>").html("<%= j(render 'favorites/favorite', question: @question) %>");

app/views/questions/_categories.html.erb
<h2 class="category-head">カテゴリー</h2>
<% categories.each do |category| %>
<p class="category-lists-box">
  <%= link_to category.name, questions_path(category_id: category.id), class: "category-lists" %><br>
</p>
<% end %>

app/views/questions/_question.html.erb
<div class="questions-item">
  <% questions.each do |question| %>
  <div class="question-titles">
    <p class="question-titles-category">
      <%= link_to question.category.name, questions_path(category_id: question.category.id), class: "category-link" %>
    </p>
    <h2><%= link_to question.title, question_path(question), class: "question-title-name" %></h2>
    <p class="question-titles-p">
      <%= link_to question.user.name, user_path(question.user), class: "p-username" %>
    </p>
    <p class="question-titles-p"><%= question.created_at.strftime('%Y/%m/%d') %></p>
  </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="page-padding">
  <div class="post-contents-box">
    <h1 class="post-contents-head">
      <i class="fas fa-pencil-alt"></i>
      <ruby>投稿編集<rt>とうこうへんしゅう</rt></ruby>
    </h1>
    <div class="question-post-fields">
      <!--エラーメッセージ-->
      <%= render 'layouts/error', obj: @question %>
      <%= form_with model: @question, local:true do |f| %>
        <div class="question-field">
          <%= f.collection_select :category_id, Category.all, :id, :name %>
        </div>
        <div class="question-field">
          <%= f.attachment_field :image %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :title %></p>
          <%= f.text_field :title, class: "question-title-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :observation %></p>
          <%= f.text_area :observation, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :impression %></p>
          <%= f.text_area :impression, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :realization %></p>
          <%= f.text_area :realization, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :uncertainty %></p>
          <%= f.text_area :uncertainty, class: "question-body-field" %>
        </div>
        <button type="submit" class="question-post-btn">
          投稿編集
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="page-padding">
  <div class="question-contents">
    <!--カテゴリー一覧-->
    <div class="categories-index categories-question-index">
      <%= render 'questions/categories', categories: @categories %>
    </div>
    <!--記事一覧-->
    <div class="questions-list">
      <h1 class="questions-list-head">
        <% if @category.present? %>
          <%= @category.name %>
        <% else %>
          なんで
        <% end %>
        <ruby>記事<rt>きじ</rt>一覧<rt>いちらん</rt></ruby>
      </h1>
      <% if @questions.present? %>
        <%= render 'questions/question', questions: @questions %>
      <% else %>
        <p>まだ記事はありません</p>
      <% end %>
      <div class="question-index-paginate paginate">
        <%= paginate @questions %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="page-padding">
  <div class="post-contents-box">
    <h1 class="post-contents-head">
      <i class="fas fa-pencil-alt"></i>
      <ruby>新規投稿<rt>しんきとうこう</rt></ruby>
    </h1>
    <div class="question-post-fields">
      <!--エラーメッセージ-->
      <%= render 'layouts/error', obj: @question %>
      <%= form_with model: @question, local:true do |f| %>
        <div class="question-field">
          <%= f.collection_select :category_id, Category.all, :id, :name %>
        </div>
        <div class="question-field">
          <%= f.attachment_field :image %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :title %></p>
          <%= f.text_field :title, class: "question-title-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :observation %></p>
          <%= f.text_area :observation, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :impression %></p>
          <%= f.text_area :impression, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :realization %></p>
          <%= f.text_area :realization, class: "question-body-field" %>
        </div>
        <div class="question-field">
          <p class="question-field-p"><%= f.label :uncertainty %></p>
          <%= f.text_area :uncertainty, class: "question-body-field" %>
        </div>
        <button type="submit" class="question-post-btn">
          新規投稿
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/search.html.erb
<div class="page-padding">
  <div class="question-contents">
    <!--カテゴリー一覧-->
    <div class="categories-index categories-question-index">
      <%= render 'questions/categories', categories: @categories %>
    </div>
    <!--記事一覧-->
    <div class="questions-list">
      <h1 class="questions-list-head"><ruby>検索結果<rt>けんさくけっか</rt></ruby></h1>
      <% if @search_questions.present? %>
        <%= render 'questions/question', questions: @search_questions %>
      <% else %>
        <p>検索結果がありません</p>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="page-padding">
  <div class="question-contents">
    <!--カテゴリー一覧-->
    <div class="categories-index categories-question-show">
      <%= render 'questions/categories', categories: @categories %>
    </div>
    <!--なんで記事詳細-->
    <div class="questions-list">
      <div class="question-show">
        <p class="question-titles-category">
          <%= link_to @question.category.name, questions_path(category_id: @question.category.id), class: "category-link" %>
        </p>
        <h1 class="question-show-header"><%= @question.title %></h2>
        <p class="question-titles-p">
          <%= link_to @question.user.name, user_path(@question.user), class: "p-username" %>
        </p>
        <p class="question-titles-p"><%= @question.created_at.strftime('%Y/%m/%d') %></p>
        <div class="question-show-image"><%= attachment_image_tag @question, :image, size: '500x350' %></div>
        <div class="question-show-observation">
          <h2 class="question-show-item">気づいたこと</h2>
          <p class="question-show-opinion"><%= simple_format(h(@question.observation)) %></p>
        </div>
        <div class="question-show-impression">
          <h2 class="question-show-item"><ruby>思ったこと</h2>
          <p class="question-show-opinions"><%= simple_format(h(@question.impression)) %></p>
        </div>
        <div class="question-show-realization">
          <h2 class="question-show-item">わかったこと</h2>
          <p class="question-show-opinion"><%= simple_format(h(@question.realization)) %></p>
        </div>
        <div class="question-show-uncertainty">
          <h2 class="question-show-item">まだわからないこと</h2>
          <p class="question-show-opinion"><%= simple_format(h(@question.uncertainty)) %></p>
        </div>
        <div class="question-show-edit-delete">
          <% if @question.user == current_user || current_user && current_user.admin? %>
            <%= link_to "編集", edit_question_path(@question), class: "question-edit edit-delete" %>
            <%= link_to "削除", question_path(@question), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "question-delete edit-delete" %>
          <% end %>
        </div>
      </div>
      <!--お気に入り-->
      <div class="favorite-btn-<%= @question.id %>">
        <%= render 'favorites/favorite', question: @question %>
      </div>
      <!--コメント-->
      <div class="comment-content">
        <%= render 'comments/index', comments: @comments %>
      </div>
      <div class="new-comment">
        <%= render 'comments/comments_form', question: @question, comment: @comment %>
      </div>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<% if user_signed_in? %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー中", user_relationships_path(user), method: :delete, remote: true, class: "followed" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user), method: :post, remote: true, class: "unfollow" %>
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<div class="user-profile-items">
  <div><%= attachment_image_tag user, :image, size: '100x100', fallback: "no_image.png", class: "user-list-img" %></div>
  <p class="user-profile-name"><%= user.name %></p>
</div>
<p><%= simple_format(h(user.introduction)) %></p>
<% if user.is_active == false %>
  <p>このユーザーは退会しました</p>
<% else %>
  <!--フォローボタン-->
  <% unless current_user && user.id == current_user.id %>
    <div class="<%= user.id %>-follow-btn follow-btn">
      <%= render 'follow', user: user %>
    </div>
  <% end %>
<% end %>
<% if user_signed_in? && (user.id == current_user.id ||  current_user.admin?) %>
  <p class="user-profile-edit-p">
    <%= link_to "プロフィール編集", edit_user_path(user), class: "user-profile-edit" %>
  </p>
<% end %>
<!--お気に入り一覧-->
<p class="profile-link-items">
  <%= link_to "お気に入りなんで事典", users_favorites_path(user), class: "profile-link" %>
</p>
<p class="profile-link-items">
  <%= link_to "フォロー一覧", user_followed_path(user), class: "profile-link" %>
</p>
<p class="profile-link-items">
  <%= link_to "フォロワー一覧", user_follower_path(user), class: "profile-link" %>
</p>
<% if user_signed_in? && user.id == current_user.id %>
  <p class="user-out">
    <%= link_to "退会する", out_user_path(user), class: "out-btn" %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div class="page-padding">
  <div class="post-contents-box">
    <h2 class="post-contents-head">プロフィール編集</h2>
    <div class="question-post-fields">
      <!--エラーメッセージ-->
      <%= render 'layouts/error', obj: @user %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="field">
          <p class="question-field-p"><%= f.label :name %></p>
          <%= f.text_field :name, autofocus: true, class: "question-title-field" %>
        </div>
        <div class="field">
          <p class="question-field-p"><%= f.label :image %></p>
          <%= f.attachment_field :image, class: "question-title-field" %>
        </div>
        <div class="field">
          <p class="question-field-p"><%= f.label :introduction %></p>
          <%= f.text_area :introduction, class: "question-body-field" %>
        </div>
        <div class="field">
          <% if current_user.admin? %>
            <%= f.label :is_active, "会員ステータス" %><br />
            <%= f.radio_button :is_active, :true %>
            <%= f.label :有効, class: "status" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :退会, class: "status" %>
          <% end %>
        </div>
        <button type="submit" class="question-post-btn">
          変更を保存
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="user-page">
  <div class="user-contents">
    <!--ユーザープロフィール表示-->
    <div class="user-profile">
      <%= render 'profile', user: @user %>
    </div>
    <!--お気に入り一覧-->
    <div class="questions-list">
      <h1 class="questions-list-head"><%= @user.name %> のお気に入りなんで事典</h1>
      <% if @favorite_questions.present? %>
        <%= render 'questions/question', questions: @favorite_questions %>
      <% else %>
        <p>お気に入り記事はまだありません</p>
      <% end %>
      <div class="user-favorite-paginate paginate">
        <%= paginate @favorite_questions %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user-page">
  <div class="user-contents">
    <!--カテゴリー一覧-->
    <div class="categories-index categories-user-index">
      <%= render 'questions/categories', categories: @categories %>
    </div>
    <!--ユーザー一覧-->
    <div class="users-list">
      <h1 class="questions-list-head">ユーザー<ruby>一覧<rt>いちらん</rt></ruby></h1>
      <div class="users-list-content">
        <% @users.each do |user| %>
        <div class="user-list-item">
          <!--管理者は一覧に表示されないようにする-->
          <% unless user.admin? %>
            <%= link_to user_path(user), class: "user-list-link" do %>
            <div class="user-list-link-items">
              <%= attachment_image_tag user, :image, size: '80x80', fallback: "no_image.png", class: "user-list-img" %>
              <p class="user-list-username"><%= user.name %></p>
            </div>
            <% end %>
            <% if user_signed_in? && current_user.admin? %>
              <div class="user-status">
                <% if user.is_active == false %>
                  <p>退会済み</p>
                <% else %>
                  <p>有効</p>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
      <div class="user-index-paginate paginate">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/out.html.erb
<div class="page-padding">
  <div class="out-box">
    <h1 class="user-out-head">本当に退会しますか？</h1>
    <p class="user-out-text">
      退会すると、会員登録情報の閲覧や<br>
      記事の投稿などができなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>
    <div class="out-btn-content">
      <%= link_to "退会しない", user_path(current_user.id), class: "out-cancel cancel-ok" %>
      <%= link_to "退会する", hide_user_path(@user), class: "out-ok cancel-ok" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-page">
  <div class="user-contents">
    <!--ユーザープロフィール表示-->
    <div class="user-profile">
      <%= render 'profile', user: @user %>
    </div>
    <!--ユーザーの投稿一覧-->
    <div class="questions-list">
      <h3 class="questions-list-head"><%= @user.name %> のなんで<ruby>事典<rt>じてん</rt></ruby></h3>
      <% if @questions.present? %>
        <%= render 'questions/question', questions: @questions %>
      <% else %>
        <p>投稿はまだありません</p>
      <% end %>
      <div class="user-show-paginate paginate">
        <%= paginate @questions %>
      </div>
    </div>
  </div>
</div>