config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'out'
      get 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'follower' => 'relationships#follower', as: 'follower'
  end
  # get 'users/:id/out' => 'users#out', as: 'out'
  # get 'users/:id/hide' => 'users#hide', as: 'hide'
  get 'users/:id/favorites' => 'users#favorite', as: 'users_favorites'
  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get 'search' => 'questions#search'
  resource :inquiries, only: [:new, :create]
  get 'thanks' => 'inquiries#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :title, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  validates :name, presence: true
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_questions, through: :favorites, source: :question
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def active_for_authentication?
    super && (self.is_active === true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_question, only: [:create, :destroy]

  def create
    # 投稿に紐づいたコメントを作成
    @comment = @question.comments.build(comment_params)
    @comment.score = Language.get_data(comment_params[:body])
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    else
      render :error
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], question_id: params[:question_id])
    comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_question, only: [:create, :destroy]

  def create
    favorite = current_user.favorites.build(question_id: @question.id)
    favorite.save
    render :index
  end

  def destroy
    favorite = current_user.favorites.find_by(question_id: @question.id)
    favorite.destroy
    render :index
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @rank = Question.joins(:favorites).group(:question_id).order(Arel.sql('count(question_id) desc')).limit(3)
  end

  def about
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :thanks]

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      InquiryMailer.received_email(@inquiry).deliver
      redirect_to thanks_path
    else
      render :new
    end
  end

  def thanks
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :favorite, :edit, :update, :out, :hide]

  def show
    @questions = @user.questions.page(params[:page]).reverse_order
  end

  def index
    @categories = Category.all
    @users = User.page(params[:page]).reverse_order
  end

  def favorite
    @favorite_questions = @user.favorite_questions.page(params[:page]).reverse_order
  end

  def edit
    if @user == current_user || current_user.admin?
      render :edit
    else
      redirect_to users_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def out
    if @user == current_user
      render :out
    else
      redirect_to users_path
    end
  end

  def hide
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image, :is_active)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="page-padding">
  <div class="about-padding">
  <div class="nande-about">
    <h1 class="about-head">なんで<ruby>事典<rt>じてん</rt></ruby>とは</h1>
    <p>
      気になったことを
      <ruby>記事<rt>きじ</rt></ruby>
      にして、自分だけの『なんで
      <ruby>事典<rt>じてん</rt></ruby>
      』を作れる
      <ruby>投稿<rt>とうこう</rt></ruby>サイトです。
    </p>
    <div class="about-box">
      <p class="about-items about-items1">なんで？</p>
      <p class="about-items about-items2">どうして？</p>
      <p class="about-items about-items3">気になる！</p>
      <p class="about-items about-items4">知りたい！</p>
    </div>
    <p>
      そんな<ruby>気持<rt>きも</rt></ruby>ちになったら、
      なんで<ruby>記事<rt>きじ</rt></ruby>を<ruby>書<rt>か</rt></ruby>いてみよう！<br>
      <ruby>不思議<rt>ふしぎ</rt></ruby>に思うこと。<ruby>試<rt>ため</rt></ruby>したいこと。
      <ruby>誰<rt>だれ</rt></ruby>かに聞いてみたいこと。<br>
      どんな小さなことでも、自分で<ruby>考<rt>かんが</rt></ruby>えてみて。そして<ruby>調<rt>しら</rt></ruby>べてみて。<br>
      <ruby>世界<rt>せかい</rt></ruby>の<ruby>不思議<rt>ふしぎ</rt></ruby>を見つけにいこう！
    </p>
  </div>

app/views/homes/top.html.erb
<div class="homes-top-page">
  <div class="welcome-contents">
    <div id="container">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
      </div>
    </div>
    <div class="homes-top-welcome">
      <h1 class="welcome-head">なんで<ruby>事典<rt>じてん</rt></ruby></h1>
      <p class="welcome-item">
        せかいにはふしぎがいっぱい！<br>
          <br>
        なんで？ どうして？?<br>
        いろんなふしぎを調べて、試して。<br>
        　<br>
        自分だけのなんで事典を作ろう！
      </p>
    </div>
  </div>
  <div class="top-text">
    <p>
      <%= link_to "ログイン", new_user_session_path %>、
      <%= link_to "新規登録", new_user_registration_path %>
      をしてなんで記事を投稿しよう！
    </p>
  </div>
  <div class="ranking-content">
    <h1 class="ranking-head">
      <i class="fas fa-crown"></i> ランキング <i class="fas fa-crown"></i>
    </h1>
    <% @rank.each.with_index(1) do |question, i| %>
    <table class="ranking-table">
      <tr>
        <td class="ranking-num"><%= i %>位</td>
        <td class="ranking-title"><%= link_to question.title, question_path(question), class: "ranking-title" %></td>
        <td class="ranking-username"><%= link_to question.user.name, user_path(question.user), class: "ranking-username" %></td>
      </tr>
    </table>
    <% end %>
  </div>
   <p class="top-inquiry-link"><%= link_to "問合せはこちら", new_inquiries_path %></p>
</div>