config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'out'
      get 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'follower' => 'relationships#follower', as: 'follower'
  end
  # get 'users/:id/out' => 'users#out', as: 'out'
  # get 'users/:id/hide' => 'users#hide', as: 'hide'
  get 'users/:id/favorites' => 'users#favorite', as: 'users_favorites'
  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get 'search' => 'questions#search'
  resource :inquiries, only: [:new, :create]
  get 'thanks' => 'inquiries#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :title, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  validates :name, presence: true
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_questions, through: :favorites, source: :question
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def active_for_authentication?
    super && (self.is_active === true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_question, only: [:create, :destroy]

  def create
    # 投稿に紐づいたコメントを作成
    @comment = @question.comments.build(comment_params)
    @comment.score = Language.get_data(comment_params[:body])
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    else
      render :error
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], question_id: params[:question_id])
    comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @rank = Question.joins(:favorites).group(:question_id).order(Arel.sql('count(question_id) desc')).limit(3)
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :favorite, :edit, :update, :out, :hide]

  def show
    @questions = @user.questions.page(params[:page]).reverse_order
  end

  def index
    @categories = Category.all
    @users = User.page(params[:page]).reverse_order
  end

  def favorite
    @favorite_questions = @user.favorite_questions.page(params[:page]).reverse_order
  end

  def edit
    if @user == current_user || current_user.admin?
      render :edit
    else
      redirect_to users_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def out
    if @user == current_user
      render :out
    else
      redirect_to users_path
    end
  end

  def hide
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image, :is_active)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <p class="error-massage"><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer-text">Copyright © NandeZiten All Rights Reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="nav-contents">
    <div class="header-logo">
      <%= link_to root_path do %>
        <%= image_tag "nande_logo.png", alt: "Nande icon", class: "header-logo", size: '180x85' %>
      <% end %>
    </div>
    <ul class="nav-list">
      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id) do %>
            <%= image_tag "nav-mypage.png", alt: "mypage", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to users_path do %>
            <%= image_tag "nav-users.png", alt: "users", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to questions_path do %>
            <%= image_tag "nav-questions.png", alt: "questions", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to new_question_path do %>
            <%= image_tag "nav-new-post.png", alt: "new-post", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= image_tag "nav-logout.png", alt: "logout",width: "100px" %>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to about_path do %>
            <%= image_tag "nav-about.png", alt: "about", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to users_path do %>
            <%= image_tag "nav-users.png", alt: "users", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to questions_path do %>
            <%= image_tag "nav-questions.png", alt: "questions", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path do %>
            <%= image_tag "nav-signup.png", alt: "sign up", width: "100px" %>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <%= image_tag "nav-login.png", alt: "login", width: "100px" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
  <div class="header-username">
    <% if user_signed_in? %>
      ようこそ、<%= current_user.name %>さん<i class="far fa-smile"></i>
    <% end %>
  </div>
  <div class="search-form">
    <%= search_form_for @search, url: search_path do |f| %>
      <%= f.search_field :title_or_observation_or_impression_or_realization_or_uncertainty_cont, size: "25", placeholder: "キーワード検索", class: "search_field" %>
      <%#= f.submit class: "search_btn" %>
      <button type="submit" class="search_btn"><i class="fas fa-search"></i></button>
    <% end %>
  </div>

</header>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="flash text-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NandeZiten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= render "layouts/notice" %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>